### ISSUE TITLE
Address claim bytes sent in wrong order.

### ISSUE THREAD

**Issue by andrew-headsight** [juergenH87/python-can-j1939#1]
When performing an address claim the bytes received on the other end are in reverse order.
Example:
```
name = j1939.Name(
    arbitrary_address_capable=0,
    industry_group=j1939.Name.IndustryGroup.AgriculturalAndForestry,
    vehicle_system_instance=0,
    vehicle_system=17,
    function=129,
    function_instance=0,
    ecu_instance=0,
    manufacturer_code=484,
    identity_number=123
    )
```

PGN: 18EEFF80h 
Data: 20 22 81 00 3C 80 00 7B

Expected Data: 7B 00 80 3C 00 81 22 20.

It looks like in names.py the bytes property (:235) is flipping the order or the value property (:208).

I swapped the order of the bytes property and it all came in correctly.
![image](https://user-images.githubusercontent.com/79323429/108523659-2d92eb80-729c-11eb-8f15-002d60ccf8df.png)

My guess is that it was assumed the Arbitrary Address Capable started at bit 0 instead of Identity Number starting at bit 0 based on the picture written in the standard.
![image](https://user-images.githubusercontent.com/79323429/108524972-9b8be280-729d-11eb-98f9-db004dee6cb7.png)

This was tested against a VT and PCAN Explorer 6 with the J1939 decoder.

**Comment by juergenH87** [comment]
Hi, 
thanks for your support!
I checked your assumption with the wrong order, but found some sources that confirm that the implementation is correct:

**1: Copperhill - A Comprehensible Guide to J1939**
![image](https://user-images.githubusercontent.com/47256248/108591630-0276cd80-736a-11eb-9460-980373457172.png)


**2: Embedded Flakes**
https://embeddedflakes.com/network-management-in-sae-j1939/
![image](https://user-images.githubusercontent.com/47256248/108591803-cd1eaf80-736a-11eb-9197-0720cfb0cb21.png)


**3: Kvaser j1939 description**
https://www.kvaser.com/about-can/higher-layer-protocols/j1939-introduction/
![image](https://user-images.githubusercontent.com/47256248/108591843-11aa4b00-736b-11eb-831d-4d4a50630a99.png)


I don't have the appropriate j1939 standard (j1939-81) at hand, but I think the sources are clear, that the message begins with the identity number.
If you agree, i would like to close the topic?

BR Jürgen

**Comment by juergenH87** [comment]
@andrew-headsight 
you mentioned the pcan explorer. I also use this and here is the corresponding symbol entry for the "address claimed message":

["Address Claimed Message"]
ID=18EEFFFEh
Type=J1939PG
Len=8
Var="Identity Number" unsigned 0,21 /max:1 /spn:1
Var="Manufacturer Code" unsigned 21,11 /max:1
Var="Function Instance" unsigned 35,5 /max:1
Var="ECU Instance" unsigned 32,3 /max:1
Var=Function unsigned 40,8 /max:1
Var="Vehicle System" unsigned 49,7 /max:1
Var=Reserved unsigned 48,1
Var="Arbitrary Address Capable" unsigned 63,1
Var="Vehicle System Instance" unsigned 56,4 /max:1
Var="Industry Group" unsigned 60,3 /max:1

**Comment by juergenH87** [comment]
Hi,
thank you for your support. You're right.
I fixed the problem, see #2

Here also the corresponding pcan symbol:

["Address Claimed Message"]
ID=18EEFFFEh
Type=J1939PG
Len=8
Var="Identity Number" unsigned 0,21 /max:1 /spn:1
Var="Manufacturer Code" unsigned 21,11 /max:1
Var="Function Instance" unsigned 35,5 /max:1
Var="ECU Instance" unsigned 32,3 /max:1
Var=Function unsigned 40,8 /max:1
Var="Vehicle System" unsigned 49,7 /max:1
Var=Reserved unsigned 48,1
Var="Arbitrary Address Capable" unsigned 63,1
Var="Vehicle System Instance" unsigned 56,4 /max:1
Var="Industry Group" unsigned 60,3 /max:1

**Comment by andrew-headsight** [comment]
Awesome! Yeah I should have referenced that symbol or a document declaring the specific byte order.
Thanks for your quick response!

**Comment by FilipZZZ** [comment]
``I'm affraid it was an incomplete fix.
Bytes are being sent in correct order, but the @bytes.setter in name.py is still processing them as big endian. Whereas on the bus name is being sent as little endian.
That cause wrong name comparison results in _process_addressclaim() method and incorrect address claiming.
```
    def _process_addressclaim(self, mid, data, timestamp):
        ...
        contenders_name = j1939.Name(bytes = data) # little endian data to big endian setter
        ...
```
For me I fixed it in the @bytes.setter like this: 
```
    @bytes.setter
    def bytes(self, value):
        #self.value = int("".join("%.2X" % _byte for _byte in value), 16)
        self.value = int.from_bytes(value, byteorder='little', signed=False)
```
This way it only accepts little endian bytes object, but thats how it is on the bus so it works for me.

**Comment by andrew-headsight** [comment]
Did you remove the initial changes I had submitted previously?
I am going to try your implementation.
