### ISSUE TITLE
Update https://pypi.org/project/can-j1939/

### ISSUE THREAD

**Issue by paulbrandkvernelandmechatronics** [juergenH87/python-can-j1939#24]
Can you please update version 2.0.5 to 2.0.6 on https://pypi.org/project/can-j1939/ ?

I'm running into:
https://github.com/FilipZZZ/python-can-j1939/commit/c28578d8f6adce6ed7037432d1d33b875186ad5e

Thanks!

**Comment by juergenH87** [comment]
thx, 2.0.6 is online

**Comment by paulbrandkvernelandmechatronics** [comment]
Perfect Thanks!
