### ISSUE TITLE
Serial over Can module compatibility? 

### ISSUE THREAD

**Issue by ril3y** [juergenH87/python-can-j1939#32]
I noticed that the supported drivers included CAN over Serial.

https://www.seeedstudio.com/Serial-CAN-BUS-Module-based-on-MCP2551-and-MCP2515.htm

Excuse my ignorance but is something like this module what you mean but can over serial? I have a Kelly motor controller that sends all of the data over the CAN J1939 protocol. I really just want to be able to sniff this data and get stuff like RPM etc on an embedded system over uart.

This is the protocol spec for the controller if you were interested.

https://kellycontroller.com/wp-content/uploads/kls-8080i-ips/Sinusoidal-Wave-Controller-KLS-D-8080I-8080IPS-Broadcast-CAN-Protocol.pdf

**Comment by juergenH87** [comment]
I'm sorry but I don't have any information about the MCP2515 controller support. 
The underlying python-can interface may or may not support this module. 
Please have a look at to the project: [https://python-can.readthedocs.io/en/master/](url) 

I suggest you test your can-interface with python-can only. Here you should receive the extended ids from the kelly controller. The python j1939 module doesn't really offer more advantages for the classic 8-byte communication.

**Comment by ril3y** [comment]
Oh I thought that I could not use python-can since the controller "spoke" j1939 extended.  Sorry I am still trying to learn CAN :)
