### ISSUE TITLE
Import of tkinter fails

### ISSUE THREAD

**Issue by wallem89** [juergenH87/python-can-j1939#33]
I have the following issue when building a new version of my application when using this library. With the latest [commit ](https://github.com/juergenH87/python-can-j1939/commit/bb6a8875d5c9928bb453890dbd389d6c718a3477) tkinter is imported on line 1 of [j1939_22.py](https://github.com/juergenH87/python-can-j1939/blob/master/j1939/j1939_22.py):
`from tkinter import E`

tkinter is not part of the install_requires. Could this be the issue?

Issue reported in Balena when running my Python application "j1939" using this library: 
j1939  Starting acpc j1939 server
 j1939  Traceback (most recent call last):
 j1939    File "./rocsys_j1939/server.py", line 3, in <module>
 j1939      import j1939
 j1939    File "/usr/local/lib/python3.7/site-packages/j1939/__init__.py", line 2, in <module>
 j1939      from .electronic_control_unit import ElectronicControlUnit
 j1939    File "/usr/local/lib/python3.7/site-packages/j1939/electronic_control_unit.py", line 10, in <module>
 j1939      from .j1939_22 import J1939_22
 j1939    File "/usr/local/lib/python3.7/site-packages/j1939/j1939_22.py", line 1, in <module>
 j1939      from tkinter import E
 j1939    File "/usr/local/lib/python3.7/tkinter/__init__.py", line 36, in <module>
 j1939      import _tkinter # If this fails your Python may not be configured for Tk
 j1939  ModuleNotFoundError: No module named '_tkinter'

**Comment by juergenH87** [comment]
sorry, i removed the import. Tkinter is not used. I think the cause was an automatic import of Visual Studio code.
