### ISSUE TITLE
Name bytes in address claiming being received in wrong order - endianness mismatch.

### ISSUE THREAD

**Issue by FilipZZZ** [juergenH87/python-can-j1939#9]
Due to incomplete fix of [Address claim bytes sent in wrong order.](https://github.com/juergenH87/python-can-j1939/issues/1)

The name bytes are being sent in correct order, but the @bytes.setter in name.py is still processing them as **big endian**. Whereas on the bus the name is present as **little endian**.
That causes wrong name comparison results in _process_addressclaim() method and **incorrect address claiming**.

    def _process_addressclaim(self, mid, data, timestamp):
        ...
        contenders_name = j1939.Name(bytes = data) # <------ !!! little endian data to big endian setter
        ...
For me I fixed it in the @bytes.setter like this:

    @bytes.setter
    def bytes(self, value):
        #self.value = int("".join("%.2X" % _byte for _byte in value), 16) # big endian comented out
        self.value = int.from_bytes(value, byteorder='little', signed=False) # use little endian
This way the setter only accepts little endian bytes object, but thats how it is on the bus so it works for me.

**Comment by juergenH87** [comment]
thanks, I have also included the abort behavior in J1939-22.

**Comment by jedpop** [comment]
This issue remains in 2.0.6.

I debugged the code and noticed the line modified was never executed.

The return value at name.py line 237 oddly had the correct order but the message on the can bus wire had the incorrect endianess.

**Comment by grant-allan-ctct** [comment]
@jedpop I'm interested to hear whether you got to a resolution, or if you believe it is still broken?  If it's still broken, I wonder if a unit test can be devised which can catch the problem.
